### ISSUE TITLE
After 1.0 create command does not parse parameters .yaml file

### ISSUE THREAD

**Issue by Yitsushi** [acquia/moonshot#186]
Before 1.0 we had a stack related parameters file _(`.yaml`)_. When we tried to create a stack with existing yaml parameters, Moonshot used them. Now for create Moonshot asks for the values but does not load default values and if I press simply `enter`, it will be `None` _(like API key for a 3rd-party service)_. For development it's a bit painful, because we use 3 or 4 external API key as a parameter and now when I try to clean up my stack (delete -> create) I have to open the secret files and copy/paste them.

The system (as I see) completely skip the yaml file. Is there any other cache solution?

**Comment by askreet** [comment]
We use AWS as a source-of-truth now for the state of running environments, rather than local files on disk which could be lost or out-of-sync.

There is a new feature that does what you want, called an "answer file". If you're trying to automate the creation of an environment, I recommend using `--no-interactive` and `--answer-file` with the `create` and `update` commands. For example, let's say you have a stack which can be configured with a BugsnagAPIKey. Create a file called "answers.yml":

```yml
---
BugsnagAPIKey: 123abcI'mabugsnagAPIkey!
```

Next, run `create` with this file passed to `--answer-file`:

    moonshot create -n my-env --answer-file answers.yml --no-interactive

(`--no-interactive` isn't strictly necessary, it just means that other missing parameters will prompt the user. This isn't great on Jenkins, for example.)

Now if you're running this locally or you only have one or two parameters, you may find the `-P/--parameter` option more helpful:

    moonshot create -n my-env -P BugsnagAPIKey=123abcI\'mabugsnagAPIkey\! -P OtherKey=Value

The same options work for `update`, but are only required if you are **changing** an option, which is in contrast to how 0.7.x worked.

**Comment by Yitsushi** [comment]
Thank you for the clarification.
