### ISSUE TITLE
Allow multiple ASGs in CodeDeploy Deployment Group

### ISSUE THREAD

**Issue by aligentjim** [acquia/moonshot#93]
Our use case for Moonshot has us deploying code to two separate ASGs (app servers and utility servers).  When I set up the CodeDeploy deployment mechanism I need to specify the logical name of a single ASG.  I've had a couple of attempts at working around this (e.g. defining my Deployment Group in the CF stack with the same name as Moonshot would have created, creating the Deployment Group via CF and not specifying an ASG at all in Moonshot).

I note there's a comment in class `Moonshot::DeploymentMechanism::CodeDeploy`:
```
  # @param app_name [String, nil] (nil)
  #   The name of the CodeDeploy Application and Deployment Group. By default,
  #   this is the same as the stack name, and probably what you want. If you
  #   have multiple deployments in a single Stack, they must have unique names.
```
Multiple deployments might be a solution to my issue, but I'm not sure how we'd implement that.  I'm not much of a Rubyist, so it's possible I'm missing something obvious in the code, in which case I'd be more than happy to update the docs with a solution if someone could point me in the right direction.

Alternatively, CodeDeploy supports multiple ASG's in a single deployment group.  Would it be better to implement support for that within Moonshot itself?  Again, happy to do the work to implement this, if we think that's the best approach.

**Comment by askreet** [comment]
Is your use case wanting to deploy the same exact artifact to both types of servers? I ask because we have a team internally using Moonshot who had similar concerns, but ended up going down the path of two stacks entirely, sharing a parent "Networking" stack, because each piece of software needed separate build and deployment steps.

I've been hesitating to solve this problem because I can't think of a good one-size-fits-all solution. Some ideas are:
- Write two `Moonshot::CLI` tools which use the same application name, but specify a different ASG Logical ID and build script, which bundles a different .appspec.yml.
- Use two stacks, as our internal team did.
- Implement the concept of "Components" in moonshot where you can mix and match different mechanisms within the same stack.

The third is something I've been thinking about for a long time but each time I go to implement it, it gets increasingly complex.

**Comment by aligentjim** [comment]
Our use case is to deploy exactly the same deployment artifact in exactly the same way across the two ASGs.  We have a "normal" ELB fronted ASG for our app server tier, and a second ASG which runs a "singleton" instance for cron job execution.  The same artifact is deployed to both, it's the manner of execution that differs, and that's baked into the AMI.

Using two separate stacks might be problematic for us, the two instance types share much of the same underlying infrastructure, so teasing them apart would likely be difficult.

Writing two separate `Moonshot::CLI` tools is something I'd considered (or just rolling them into the same `environment` script).  Ideally though what I'd really like to do is:

```self.deployment_mechanism = CodeDeploy.new(asg: ['AppServerASG', 'CronServerASG'] , role: 'CodeDeployRole')```

Since the underlying CodeDeploy service supports multiple ASGs in a deployment group, the change to Moonshot largely involves correctly validating that both ASGs exist in the deployment group, and waiting on both ASGs to reach capacity after deployment.

Another alternative I'd considered was to create a "multi-deploy" deployment mechanism.  Something like:

```self.deployment_mechanism = MultiDeploy.new([
  CodeDeploy.new(asg: 'AppServerASG', role: 'CodeDeployRole'),
  CodeDeploy.new(asg: 'CronServerASG', role: 'CodeDeployRole')
])```

Handling failure cases for the `MultiDeploy` mechanism might get messy, but we could live with a fairly naive implementation at this point.  Is this something like you were considering with components?

This is a problem we will be looking to solve fairly quickly.  So if there's a solution which fits the overall direction for Moonshot, where we can solve our problem and make a contribution to the development of Moonshot we'd be happy to do that.

**Comment by askreet** [comment]
Closing this as it was addressed in the linked PR.
